# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
      - ".github/workflows/**"

defaults:
  run:
    working-directory: frontend

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run frontend tests
        uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - run: yarn
      - run: yarn build
      - run: yarn test
